### ISSUE TITLE
Events can't be sent

### ISSUE THREAD

**Issue by mmorainville** [NeutrinoMetrics/electron-analytics#1]
Hi,

I'm currently testing out NeutrinoMetrics on one of my app which is in closed beta for the moment and apparently the `send` method is not working, the event's call can't be made.

The init part in my main process (`EA.init('...')`) is working well as I can see stats in my dashboard but when I try to send an event from my renderer process `EA.send('CLICKED_COPY_ID')` I've got either a 500 error or simply a fail request.

`OPTIONS http://34.195.107.11:3002/event net::ERR_CONNECTION_TIMED_OUT`

Do you know where it could come from? I don't use a proxy and I'm using vue-electron (https://github.com/SimulatedGREG/electron-vue).

Thanks and regards,
M.

**Comment by mengfoobar** [comment]
@mmorainville thanks for letting us know. We are currently experiencing higher # of requests than expected for our beta. Working on optimizing our engine. Should be working now. Working on a fix that will improve stability significantly :)

**Comment by mmorainville** [comment]
Hi @mengfoobar,

Thanks for the quick response! Ok I'll wait then, I tested just now but the request still fails with a timeout.
Maybe I'm just testing at the wrong time. You could close this issue if you can't reproduce it on your side I think.

Regards,
M.
